export const FETCH_USERS: string = 'USERS/FETCH_USERS'
export const SHOW_LOADER: string = 'APP/SHOW_LOADER'
export const HIDE_LOADER: string = 'APP/HIDE_LOADER'
export const SHOW_ALERT: string = 'APP/SHOW_ALERT'
export const HIDE_ALERT: string = 'APP/HIDE_ALERT'
export const PLUS_PAGE: string = 'USERS/PLUS_PAGE'
export const CHANGE_PAGE: string = 'USERS/CHANGE_PAGE'
